spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catchkorea?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ghddydwns0928!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
